id: P1855E772
initial_creation_type: input
source_metadata:
  title: Chatral Rinpoche
  language: es
  description: 'Texts by and about the great Dzogchen master Chatral Sangye Dorje
    (bya bral sangs rgyas rdo rje, 1913–2015):'
  volume:
    a3437e6b08b3469986d994ac0b812c64:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    bc01da7d21344bfdac1de584973a5c45:
      title: The Benefits of Saving Lives
      parent: Advice
    608dc14d2efe40b5b233ef64d53b0fb3:
      title: Words of Advice
      parent: Advice
    cb3b392eabef41a48de84a1f6cba6c89:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Aspiration Prayers
    c1ad02490b4540afbabef8c393586964:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Calling the Guru from Afar
    0570878c6e3845e38815eed89a18b629:
      title: A Profound and Concise Guru Yoga
      parent: Guru Yoga
    98f6e2d333e34731b733bbbfa5889abf:
      title: Introduction to The Excellent Path of Devotion
      parent: Introductions
    dba6c2f2cad7417ea88ac6b8adc302a2:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Long Life Prayers
    f5e58f39703748469cfe1edb1d1e97e2:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Long Life Prayers
    f9c467b4ec014560b03caca563e44b91:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Pilgrimage
    9d768c13f67244b2ad24a592fdfc04a7:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Pilgrimage
    8436a18f2adf4c8f9a11c1d8beb8a171:
      title: Essence of All the Buddhas of Past, Present and Future
      parent: Prayers
    b227337e507c4dbdb46fa70c1a6d46e6:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Sādhanas
    7a75dbdd32824e96a7e9590c7b6819e4:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-02-28T22:42:38.130183'
last_modified_at: '2022-02-28T22:42:38.130186'
